jpata/particleflow

test/postprocessing2.py
- use `uproot` for postprocessing instead of `ROOT`
- timing test on `login-1.hep.caltech.edu` shows marginal speed up (this can definitely be improved):
```
time python test/postprocessing2.py --input data/TTbar_14TeV_TuneCUETP8M1_cfi/pfntuple_1.root --events-per-file 1 --save-full-graph --save-normalized-table
```
gives (with `uproot`)
```
real	7m26.182s
user	7m6.403s
sys	0m21.354s
```
vs. (with `ROOT`)
```
real	8m30.159s
user	7m54.312s
sys	1m0.828s
```
- still need to check that the output files are reproduced!
=> use uproot for postprocessing instead of ROOT

test/graph_data.py
- add `num_proc` command-line argument for parallel processing with less than 24 cores
=> Add num_proc

test/eval_end2end.py, test/plot_utils.py, test/plots.py, test/train_end2end.py
* add some command-line options to training script
* save model kwargs in pickled dictionary to restore easily in eval script
* fix eval script and add command-line options
* add comet_ml for monitoring/comparing experiments
=> PyTorch development

test/eval.sh, test/mpnn.py, test/pred_tf_model.py, test/tf_model.py, test/train.sh
Pull request integrating the MPNN code from Kyriacos. To be updated with results.
=> message passing TF model

.travis.yml, README.md, test/evaluate_timing.py, test/graph_data.py, test/train.sh, test/train_end2end.py
Bring the pytorch model up to speed with the updates to the data format. Also adding a travis test of the data prep + training pipeline. Should be done ~today. @jmduarte
=> Pytorch fixes

test/graph_data.py, test/gravnet.py, test/train.sh, test/train_end2end.py
trying a few things with the pytorch model
=> pytorch model search

test/eval_both.sh, test/mpnn.py, test/plots.py, test/tf_model.py, test/train_both.sh
I have created the eval_both.sh and train_both.sh shell scripts to run both models with a single script so that they can be directly compared
=> Mpnn update to run&evaluate both models

test/train_end2end.py
adding an additional graph convolution and skip connections - training this now over the weekend for a comparison.
@jmduarte
=> Architecture studies for the pytorch model

test/train_end2end.py
- add (full) conf matrix to comet ml
- example training: https://www.comet.ml/jmduarte/particleflow/46d21cecb83e454b8a21d81f32e7a9e9
=> add conf matrix

test/train_end2end.py
- now compute confusion matrix for full epoch (not just last batch)
- starting a new experiment with 512 hidden dim. (gen-level targets): https://www.comet.ml/jmduarte/particleflow/5c00f4938c70434d9caa48e15315736e
=> full epoch conf matrix

delphes/Makefile, delphes/main.cc, delphes/ntuplizer.py, delphes/run_ntuple.sh, delphes/run_sim.sh, delphes/tev14_pythia8_ttbar.py
- generate 500 ttbar events with pythia then run delphes and ntuplizer
- steps:
```
singularity exec http://jpata.web.cern.ch/jpata/centos7hepsim.sif ./run_sim.sh
singularity exec http://jpata.web.cern.ch/jpata/centos7hepsim.sif ./run_ntuple.sh
```
- config from here: https://atlaswww.hep.anl.gov/hepsim/info.php?item=281, except modifying mTop = 172.5
- may want to grab min bias from here: https://atlaswww.hep.anl.gov/hepsim/info.php?item=335
=> generate ttbar events then run delphes, ntuplizer

.github/workflows/test.yml, README_delphes.md, parameters/test.yaml, scripts/local_test_delphes_tf.sh
make the github action test run faster
=> speed up test

mlpf/tallinn/cms-gnn-dense.sh, parameters/cms-gnn-dense.yaml
- Learning rate chosen with the new `find_lr` method.
- Train with new pipeline: `/eos/user/j/jpata/mlpf/models/cms/2021_07_26/cms-gnn-dense_20210723_191058.gpu0.local`
=> update lr, trainable (CMS, TF)

LICENSE
- might be good to have a license. Apache 2.0 is used by CMSSW, hls4ml, etc.
=> add license (Apache 2.0)

mlpf/juwels/pipeline_raytune_analysis.sh
SLURM sbatch file to run Ray Tune analysis on the JUWELS Booster.
=> feat: Ray Tune analysis on JUWELS

mlpf/pipeline.py, mlpf/tallinn/cms-mlpf-test.sh, mlpf/tfmodel/model_setup.py
The evaluation did not run properly after #123.
=> fix small bug in eval

mlpf/data_clic/postprocessing.py
A bug got introduced when the duplicated charge feature was removed.
=> Fix legacy CLIC dataset pdgid

.github/workflows/test.yml, fcc/p8_ee_ZH_Htautau_ecm380.cmd, fcc/p8_ee_gg_ecm365.cmd, fcc/p8_ee_qcd_ecm365.cmd, fcc/p8_ee_qcd_ecm380.cmd, fcc/postprocessing.py, fcc/run_sim.sh, mlpf/customizations.py, mlpf/heptfds/clic_pf/higgsbb.py, mlpf/heptfds/clic_pf/higgsgg.py, mlpf/heptfds/clic_pf/higgszz4l.py, mlpf/heptfds/clic_pf/qcd.py, mlpf/heptfds/clic_pf/ttbar.py, mlpf/heptfds/clic_pf/zpoleee.py, mlpf/heptfds/clic_pf_edm4hep/qcd.py, mlpf/heptfds/clic_pf_edm4hep/ttbar.py, mlpf/heptfds/clic_pf_edm4hep/utils_edm.py, mlpf/heptfds/clic_pf_edm4hep/zh_htautau.py, mlpf/heptfds/clic_pf_edm4hep/zzfullhad.py, mlpf/pipeline.py, mlpf/plotting/plot_utils.py, mlpf/tfmodel/datasets/BaseDatasetFactory.py, mlpf/tfmodel/model.py, mlpf/tfmodel/model_setup.py, parameters/clic.yaml, scripts/generate_tfds.sh, scripts/local_test_clic_pipeline.sh
Implement postprocessing of EDM4HEP samples from the Key4HEP CLIC simulation.
Here is a multiplicity plot of tracks, clusters, PF particles and gen particles per event:
Below is a plot of PF jets, matched to gen-jets, showing that PF jets reproduce gen-jets well:
=> edm4hep postprocessing

mlpf/pyg_ssl/args.py, mlpf/pyg_ssl/evaluate.py, mlpf/pyg_ssl/mlpf.py, mlpf/pyg_ssl/training_VICReg.py, mlpf/pyg_ssl/training_mlpf.py, mlpf/pyg_ssl/utils.py, mlpf/ssl_evaluate.py, mlpf/ssl_pipeline.py, notebooks/ssl-VICreg.ipynb
- updated data split mode
- added evaluation script in case we need to just evaluate the mlpf models using fastjet
- updated the evaluation to be done separately on QCD and TTbar
=> Update data split mode for SSL studies [pytorch]

notebooks/clic.ipynb
=> update clic plots

.github/workflows/test.yml
=> Pin torch to 1.13.0

mlpf/heptfds/clic_pf_edm4hep_hits/single_ele.py, mlpf/heptfds/clic_pf_edm4hep_hits/single_gamma.py, mlpf/heptfds/clic_pf_edm4hep_hits/single_kaon0L.py, mlpf/heptfds/clic_pf_edm4hep_hits/single_mu.py, mlpf/heptfds/clic_pf_edm4hep_hits/single_neutron.py, mlpf/heptfds/clic_pf_edm4hep_hits/single_pi.py, mlpf/heptfds/clic_pf_edm4hep_hits/single_pi0.py, mlpf/pipeline.py, mlpf/tfmodel/callbacks.py, mlpf/tfmodel/datasets/BaseDatasetFactory.py, mlpf/tfmodel/model_setup.py, mlpf/tfmodel/utils.py, parameters/clic-hits.yaml, parameters/clic-test.yaml, scripts/lumi/train-gpu-2.sh, scripts/lumi/train-gpu-3.sh, scripts/lumi/train-gpu-4.sh, scripts/lumi/train-gpu-5.sh, scripts/lumi/train-gpu-6.sh, scripts/lumi/train-gpu-7.sh, scripts/lumi/train-gpu-8.sh, scripts/tallinn/mlpf-train-a100-hvd2.sh, scripts/tallinn/mlpf-train-a100-mir2.sh, scripts/tallinn/mlpf-train-a100.sh
- fix horovod training on nvidia GPU
- scale test scripts on LUMI (AMD GPU)
=> scale test on lumi, fix horovod

notebooks/clic/clic-visualize.ipynb
update notebook to make charged particle path helices
=> update click vis

mlpf/pipeline.py, mlpf/tfmodel/datasets/BaseDatasetFactory.py, mlpf/tfmodel/model_setup.py, mlpf/tfmodel/utils.py, parameters/clic-test.yaml, parameters/clic.yaml, scripts/lumi/train-gpu-1.sh, scripts/lumi/train-gpu-2.sh, scripts/lumi/train-gpu-3.sh, scripts/lumi/train-gpu-4.sh, scripts/lumi/train-gpu-5.sh, scripts/lumi/train-gpu-6.sh, scripts/lumi/train-gpu-7.sh, scripts/lumi/train-gpu-8.sh
- scaling test on LUMI with the dataset v1.5.0 and a well-defined configuration
- ensure dataset is cached and not streaming for benchmark
=> new scaling test on LUMI

mlpf/pipeline.py, mlpf/pyg/evaluate.py, mlpf/pyg/mlpf.py, mlpf/pyg/ssl/evaluate.py, mlpf/pyg/training.py, mlpf/pyg_pipeline.py, mlpf/tfmodel/datasets/BaseDatasetFactory.py, mlpf/tfmodel/model.py, mlpf/tfmodel/model_setup.py, parameters/clic-hits.yaml, parameters/clic-test.yaml, parameters/clic.yaml, parameters/cms-gen.yaml, parameters/delphes.yaml, requirements.txt, scripts/generate_tfds.sh, scripts/tallinn/cms-gen.sh
- some fixes for CMS training: the energy feature index has changed, normalizer is currently not supported for CMS
- enable the torch model to be exported to ONNX. currently only works for the GNN-LSH model.
=> small fixes for CMS training, torch onnx export

mlpf/pyg/training.py, parameters/pyg-config.yaml
Fixing ddp.dist.barrier() hang by running validation forward pass using model.module() instead of model(). This is needed because validation is only run on single gpu (unlike training & inference).
=> fix pytorch multi-GPU training hang

mlpf/pyg/utils.py, mlpf/pyg_pipeline.py
--ntrain: training samples
--ntest validation samples
=> feat: specify number of samples as cmd line arg in pytorch training and testing

mlpf/pyg/gnn_lsh.py, mlpf/pyg/inference.py, mlpf/pyg/mlpf.py, mlpf/pyg/training.py, mlpf/pyg_pipeline.py, scripts/local_test_pyg.sh, scripts/tallinn/rtx/pytorch.sh, tests/test_torch_and_tf.py
- make sure that at least the GNN-LSH model can be exported to ONNX
=> restore onnx export in pytorch

mlpf/pyg/mlpf.py, parameters/pyg-cms-small.yaml, scripts/tallinn/rtx/pytorch.sh
- compare GNNLSH, Gravnet and Attention on a sort of equal basis
=> compare all three models in pytorch

mlpf/pyg/inference.py, mlpf/pyg_pipeline.py
Allows testing on a given `--load-checkpoint`. If not provided will test using the `best_weights.pth` and store the results under `preds_bestweights/` and `plots_bestweights/`
=> Allows testing on a given --load-checkpoint

mlpf/pyg/inference.py, mlpf/pyg/training.py
From the [PF-paper](https://arxiv.org/pdf/1706.04965.pdf) (page 28) 
`Particle-flow jets are studied down to a pT of 15 GeV.`
=> Update the jet pt threshold to be the same as the PF paper

mlpf/pyg/mlpf.py, mlpf/pyg/training.py, parameters/pytorch/pyg-clic-hits.yaml, parameters/pytorch/pyg-clic.yaml, parameters/pytorch/pyg-cms.yaml, parameters/pytorch/pyg-delphes.yaml
- make the pytorch regression output configurable
=> pytorch regression output layer configurability

parameters/pytorch/pyg-clic-hits.yaml, parameters/pytorch/pyg-clic.yaml, parameters/pytorch/pyg-delphes.yaml, scripts/tallinn/rtx/pytorch.sh
Fix up the configs for other datasets.
=> fix up configs

mlpf/data_cms/README.md, mlpf/data_cms/prepare_args.py, notebooks/cms/cms-dataset.ipynb, scripts/cmssw/validation_job.sh, scripts/tallinn/submit_validate_cms.sh
- added a notebook in `notebooks/cms/cms-dataset.ipynb` to explain how to load the dataset
- added some instructions about pytorch CMS training in `mlpf/data_cms/README.md`
=> CMS training instructions

mlpf/data_cms/genjob.sh, mlpf/data_cms/genjob_nopu.sh, mlpf/data_cms/genjob_pu55to75.sh, mlpf/data_cms/prepare_args.py, mlpf/heptfds/cld_pf_edm4hep/ttbar.py, mlpf/heptfds/cms_pf/multiparticlegun.py, mlpf/heptfds/cms_pf/qcd.py, mlpf/heptfds/cms_pf/qcd_nopu.py, mlpf/heptfds/cms_pf/vbf_nopu.py, mlpf/plotting/plot_utils.py, mlpf/pyg/PFDataset.py, mlpf/pyg/inference.py, mlpf/pyg/training.py, mlpf/pyg/utils.py, parameters/pytorch/pyg-clic.yaml, parameters/pytorch/pyg-cms-finetune.yaml, parameters/pytorch/pyg-cms.yaml, scripts/clic/postprocessing.py, scripts/fccee_cld/postprocessing.py, scripts/fccee_cld/postprocessing_jobs.py, scripts/generate_tfds.sh, scripts/tallinn/a100/pytorch-small-eval-clic.sh, scripts/tallinn/a100/pytorch-small-eval-cms.sh, scripts/tallinn/a100/pytorch-small.sh, scripts/tallinn/a100/pytorch.sh, scripts/tallinn/rtx/pytorch-eval.sh
Results in https://indico.cern.ch/event/1444807/#2-cms-status-and-plans.
=> Retraining with CMS samples v2.0.0

mlpf/data_cms/genjob_pu55to75.sh, mlpf/data_cms/postprocessing_jobs.py, mlpf/data_cms/prepare_args.py, mlpf/pyg/PFDataset.py, mlpf/pyg/inference.py, mlpf/pyg/mlpf.py, mlpf/pyg/training.py, parameters/pytorch/pyg-clic.yaml, parameters/pytorch/pyg-cms.yaml, scripts/tallinn/a100/pytorch-small.sh, scripts/tallinn/a100/pytorch.sh
- instead of pt, predict and run loss on log(pt/elem pt), as this quantity is distributed approximately as a Gaussian (same for E)
- save a few validation events at each epoch for checks to understand why the validation loss is fluctuating a lot
=> try to improve val loss stability

.github/workflows/test.yml, requirements.txt, scripts/local_test_pyg.sh
Addresses #348.
Also updates the github workflow correspondingly.
=> add torch to requirements

mlpf/data/cms/README.md
Add a compatibility table in the CMS readme.
=> add compatibility table

mlpf/model/training.py, mlpf/pipeline.py, scripts/local_test_torch.sh, scripts/lumi/pytorch-clic-8.sh, scripts/lumi/pytorch-cms-8.sh, scripts/tallinn/a100-mig/pytorch-small-eval-clic.sh, scripts/tallinn/a100-mig/pytorch-small-eval-cms.sh, scripts/tallinn/a100-mig/pytorch-small.sh, scripts/tallinn/a100/pytorch-clic.sh, scripts/tallinn/a100/pytorch.sh
The dataset is specified in the parameter configuration files only.
=> fix: remove command line argument --dataset

README.md, mlpf/model/training.py, scripts/tallinn/deploy_clic.sh, scripts/tallinn/deploy_cms.sh
- fix minor bug in clic eval
- deploy scripts
=> final fixes for v2.1.0

mlpf/model/monitoring.py, scripts/lxplus/cmssw-el8.sh, scripts/lxplus/train.sh
Test scripts for running on lxplus/lxplus-gpu.
=> added lxplus scripts

README.md
As several groups have recently asked for access to the code & datasets that is more recent than our latest publication, I think it would be good to clarify the citation policy.
FYI @jmduarte
=> Clarify citation policy

notebooks/clic/clic-losses.ipynb
- update notebook to make large batch size / multi-GPU loss plots from tensorboard
=> CLIC loss plots

.github/workflows/pre-commit.yml, mlpf/model/distributed_ray.py, mlpf/model/training.py, mlpf/model/utils.py, mlpf/optimizers/lamb.py, mlpf/pipeline.py, mlpf/raytune/pt_search_space.py, scripts/flatiron/pt_raytune_a100_4GPUsperTrial.sh, scripts/flatiron/scan_variables.py
- Integrate LAMB optimizer for large batch size training
- Integrate reduce lr on plateau lr schedule
- Make choosing the optimizer configurable from the command line and config file
- Make lr schedule configurable from command line
- Update the pre-commit workflow to solve for [these breaking changes in GitHub Actions](https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts).
=> feat: LAMB optimizer & reduce lr on plateau schedule
