jpata/particleflow

- test/postprocessing2.py
* fix overflow from `pz = pt * math.sinh(eta)` by replacing `eta` with `np.nan` (reproduces ROOT behavior of returning `pz = nan`)
> fix overflow

- mlpf/tfmodel/model.py
- mlpf/tfmodel/model_setup.py
- scripts/local_test_cms_tf.sh
- scripts/test_load_tfmodel.py
Fixes the tf map function call, which prevented an execution with a dynamic number of input elements. Added a test for loading the model from the frozen graph and executing it as is done in CMSSW.
> fix model loading and eval with a dynamic input size

- delphes/ntuplizer.py
Instead of going through GenParticle links, just assign the PFCandidate to the tower with which it has the exact same eta/phi. For the delphes PF algo, this always results in an unambiguous, complete matching. This does not change the physics results (the effect is too small to notice).
> another minor improvement to pfcand association

- mlpf/tfmodel/model.py
- Rewrite `tf.einsum` using `tf.math.multiply`
- Needed for compatibility with earlier ONNX opsets (like v11)
- May actually be slightly faster this way
> Rewrite `tf.einsum` using `tf.math.multiply`

- mlpf/tfmodel/model_setup.py
If I am not mistaken, there is a typo in the `CustomCallback` class which causes the training to crash when the function `plot_event_visualization` it is called. This PR should fix that.
> Fix bug in CustomCallback class

- mlpf/data_clic/postprocessing.py
- mlpf/pipeline.py
- mlpf/tfmodel/utils.py
- notebooks/clic.ipynb
Fix the num_cpus flag to actually tell tensorflow to use a fixed number of threads. Useful to limit the application to a fixed CPU budget on a HPC.
In the previous version, using MirroredStrategy on CPU just blows up the RAM by a factor of Nthreads, which does not seem correct.
> fix num_cpus flag

- mlpf/pyg_ssl/mlpf.py
- mlpf/pyg_ssl/training_mlpf.py
- mlpf/ssl_pipeline.py
- add some more complexity to the pytorch MLPF model
- convolution layers separated for ID and regression part
> tune the pytorch MLPF model to be more similar to TF

- fcc/main19.cc
- fcc/p8_ee_ZH_Htautau_ecm380.cmd
- fcc/p8_ee_gg_ecm365.cmd
- fcc/p8_ee_gg_ecm380.cmd
- fcc/run_sim.sh
- mlpf/pyg_ssl/args.py
- mlpf/pyg_ssl/evaluate.py
- mlpf/pyg_ssl/gravnet.py
- mlpf/pyg_ssl/mlpf.py
- mlpf/pyg_ssl/training_mlpf.py
- mlpf/pyg_ssl/utils.py
- mlpf/ssl_pipeline.py
- mlpf/tallinn/mlpf-train.sh
- mlpf/tfmodel/model_setup.py
- notebooks/clic.ipynb
- parameters/clic.yaml
- parameters/cms-gen.yaml
- parameters/delphes.yaml
- switch MLPF optimizer to AdamW [pytorch]
- use focal loss [pytorch]
- separate decoding layers for different regression components [pytorch]
- added main19.cc for generating CLIC events with PU
- switch CLIC jet clustering to ee_genkt [TF] [pytorch]
> tuning the downstream MLPF model [pytorch]

- .github/workflows/test.yml
- mlpf/heptfds/clic_pf_edm4hep/utils_edm.py
- mlpf/heptfds/cms_pf/cms_utils.py
- mlpf/heptfds/delphes_pf/delphes_pf.py
- mlpf/heptfds/delphes_pf/delphes_utils.py
- mlpf/pyg/PFGraphDataset.py
- mlpf/pyg/args.py
- mlpf/pyg/training.py
- mlpf/pyg_pipeline.py
- mlpf/tfmodel/model_setup.py
- requirements.txt
- scripts/local_test_delphes_pipeline.sh
Removed some duplication of code in the dataset prep between TF and pyg.
I think there's a bug in how the pyg loops over e.g. the CLIC dataset.
here: https://github.com/jpata/particleflow/blob/main/mlpf/pyg/training.py#L165-L172 there's currently a loop over files, and then a loop over events in the file
If I run the following, I expect the code should process 2 files per batch (200 events per batch).
```
python3 mlpf/pyg_pipeline.py --dataset CLIC --data_path data/clic_edm4hep/ --outpath experiments/pytorch_2 --bs 2 --n_train 1800 --n_valid 100 --n_test 100
```
You can see it's loading 1800 train files (`train_dataset= 1800`), and then batching them by 2 (`file_loader_train= 900`).
The outer loop has 900 steps, as expected.
**Problem**: The inner loop has 100 steps, this is not expected. …
> clean up dataset prep

- mlpf/pipeline.py
- mlpf/tfmodel/model.py
- mlpf/tfmodel/utils.py
- notebooks/clic/paper_plots_2023_ml_training.ipynb
- parameters/clic-hits.yaml
- parameters/clic-test.yaml
- parameters/clic.yaml
- parameters/cms-gen.yaml
- parameters/delphes.yaml
One can now change `event_pad_size` in 
```
train_test_datasets:
physical:
batch_per_gpu: 50
event_pad_size: -1
```
to make every batch of events be padded to the same size in terms of number of elements per event.
The previous/default behaviour, enabled when ` event_pad_size: -1`, is to pad events in each batch to the largest event in the batch.
This behaviour is enabled only when using static batching, i.e. `bucket_by_sequence_length: no`.
I'm running another scaling test on LUMI with the following config:
```diff
--- a/parameters/clic-test.yaml
+++ b/parameters/clic-test.yaml
@@ -61,7 +61,7 @@ setup:
batching:
-  bucket_by_sequence_length: yes
+  bucket_by_sequence_length: no
bucket_batch_sizes: auto
batch_multiplier: 1
@@ -205,7 +205,7 @@ raytune:
train_test_datasets:
physical: …
```
> add option to pad everything to a constant size

- mlpf/pipeline.py
- mlpf/tfmodel/utils.py
To decrease effective batch size for all samples on a small GPU.
> allow floating point batch multiplier

- requirements.txt
matplotlib 3.8.0, released just now, is incompatible with the current mplhep.
Reported to mplhep devs here: https://github.com/scikit-hep/mplhep/issues/441
> pin matplotlib due to breaking changes in mpl 3.8.0

- .github/workflows/test.yml
- .gitignore
- mlpf/pyg/PFGraphDataset.py
- mlpf/pyg/args.py
- mlpf/pyg/mlpf.py
- mlpf/pyg/model.py
- mlpf/tfmodel/model.py
- notebooks/clic/paper_plots_2023_ml_training.ipynb
- scripts/fcc/postprocessing.py
- scripts/fcc/run_pandora_timing.sh
- scripts/fcc/run_sim_gun_np.sh
- scripts/local_test_clic_hits_pipeline.sh
- scripts/local_test_pyg_clic.sh
- scripts/local_test_pyg_cms.sh
- scripts/local_test_pyg_delphes.sh
- scripts/local_test_pyg_ssl.sh
- tests/test_tf.py
- tests/test_torch_and_tf.py
- migrate to pytorch 2.0.1
- add basic unit tests on shape for TF
- implement a first version of the LSH-based GNN in pytorch, cross-checked with unit tests against TF
Here are some results on a short training (~1h) with a few events:
> WIP on torch GNN-LSH model

- mlpf/pipeline.py
- mlpf/pyg/utils.py
- mlpf/pyg_pipeline.py
- mlpf/tfmodel/utils.py
- mlpf/utils.py
- scripts/local_test_pyg.sh
In the PyTorch training pipeline, automatically give training directories a unique name when they are created.
The `--model-prefix` argument is changed to a `--prefix` argument. The string given to `--prefix` will be appended at the beginning of the automatically generated name for the training directory.
> Automatically name training dir in pytorch pipeline

- mlpf/pyg/PFDataset.py
- mlpf/pyg/gnn_lsh.py
- mlpf/pyg/mlpf.py
- mlpf/pyg/training.py
- mlpf/pyg/utils.py
- mlpf/pyg_pipeline.py
- scripts/tallinn/a100/pytorch.sh
- scripts/tallinn/rtx/pytorch.sh
- The conversion of 3D-padded shapes `[batch, elems_per_event, features]` with a padding mask to pytorch geometric sparse `[all_elems, features]` was slow. Now this is not done any more when it's not needed
- The geometric-style models (e.g. gravnet) use sparse data throughout, while the 3D-shape models (e.g. Attention, GNNLSH) use 3D-padded data throughout.
- use pin_memory in the DataLoader, which removes the host-to-device blocking call when doing `batch.to(...)`
- move the validation loop outside the train loop
- possibly some follow-up with `world_size` is still required
After all changes, here's how the profiles look like on a single batch.
Gravnet, approx. 90ms / batch, including the backward pass:
GNNLSH, approx. 125ms / batch, including the backward pass:
Longer test on RTX2060S: …
> making the 3d-padded models more efficient in pytorch

- mlpf/pyg/inference.py
- mlpf/pyg/mlpf.py
- mlpf/pyg/training.py
- mlpf/pyg_pipeline.py
- mlpf/tfmodel/model.py
- parameters/pyg-cms-small.yaml
- scripts/tallinn/rtx/pytorch.sh
Residual fixes after https://github.com/jpata/particleflow/pull/256.
Training the gnn_lsh for three epochs on pyg-cms-small.yaml I get the following performance:
> Fix pytorch inference after #256

- mlpf/pyg/training.py
- mlpf/pyg/utils.py
- mlpf/pyg_pipeline.py
- parameters/pyg-clic.yaml
- parameters/pyg-cms-small.yaml
- parameters/pyg-cms-test-qcdhighpt.yaml
- parameters/pyg-cms.yaml
- parameters/pyg-delphes.yaml
- parameters/pyg-workflow-test.yaml
- scripts/flatiron/pt_raytune_1GPUperTrial.sh
- scripts/flatiron/pt_train_4GPUs.slurm
- Checkpoint the PyTorch training at regular frequencies given by `checkpoint_freq`, specified in the config or on the command line with `--checkpoint-freq`.
- Progress messages now show `train` or `valid` instead of `train=True` or `train=False`.
- Separated out saving and loading of checkpoints into functions, saving the model, the optimizer (optional) and a `dict` named `extra_state` that can contain any additional information (optional). `extra_state` currently only contains the epoch number when the checkpoint was saved.
> Implementing configurable checkpointing.

- mlpf/pyg/training.py
- mlpf/pyg_pipeline.py
- parameters/pyg-clic.yaml
- parameters/pyg-cms-physical.yaml
- parameters/pyg-cms-small-highqcd.yaml
- parameters/pyg-cms-small.yaml
- parameters/pyg-cms-test-qcdhighpt.yaml
- parameters/pyg-cms.yaml
- parameters/pyg-delphes.yaml
- scripts/flatiron/pt_raytrain_a100.slurm
- scripts/flatiron/pt_raytrain_h100.slurm
- scripts/flatiron/pt_train.slurm
This PR includes:
- Fix issue with the CometML logging where validation losses were logged incorrectly
- Update all config files to use an integer value for the gpu parameter instead of a string
Below follows a small comparison between training using Ray Train (in yellow) and using PyTorch DDP (in gray). The first figure uses *training step* on the x-axis, making it easy to see that both algorithms follow very similar learning curves. The second plot displays *walltime* on the x-axis, clearly demonstrating that the Ray Train algorithm is much faster. In this small test which was made using the gravnet-based model and 2500 training samples while training for 10 epochs, Ray Train was ~2.3x faster than DDP. Each training run was carried out on a single compute node with 8 NVIDIA H100 GPUs. …
> Better CometML logging + Ray Train vs DDP comparison

- mlpf/pyg/mlpf.py
- mlpf/pyg/training.py
- mlpf/pyg/utils.py
- mlpf/pyg_pipeline.py
- mlpf/raytune/pt_search_space.py
- parameters/pyg-clic.yaml
- parameters/pyg-cms-physical.yaml
- parameters/pyg-cms-small-highqcd.yaml
- parameters/pyg-cms-small.yaml
- parameters/pyg-cms-test-qcdhighpt.yaml
- parameters/pyg-cms.yaml
- parameters/pyg-delphes.yaml
- parameters/pyg-workflow-test.yaml
- scripts/flatiron/pt_raytrain_a100.slurm
- scripts/flatiron/pt_raytrain_h100.slurm
- scripts/flatiron/pt_raytune_a100_1GPUperTrial.sh
- scripts/flatiron/pt_raytune_a100_4GPUsperTrial.sh
- scripts/flatiron/pt_raytune_h100_1GPUperTrial.sh
- scripts/flatiron/pt_raytune_h100_2GPUsperTrial.sh
- scripts/flatiron/pt_raytune_h100_4GPUsperTrial.sh
- scripts/flatiron/pt_raytune_h100_8GPUsperTrial.sh
- scripts/flatiron/pt_test.slurm
- scripts/flatiron/pt_train.slurm
Implement LR schedules in the PyTorch training code. Add MambaLayer and make it configurable through parameter config files and for HPO.
Also contains the following changes.
- `--load` now takes as input the path to a saved checkpoint from which to start a new training. I.e., a training starts from epoch 1, with LR schedules starting from the beginning. The only thing that is loaded is the pre-trained model weights from the checkpoint.
- `--resume-training` is a new command line arg that takes as input a path to a training directory containing an unfinished training and attempts to restore it and continue the training from the last saved checkpoint.
*Learning rate versus training step of a training using the `cosinedecay` LR schedule and was interrupted halfway through and then …
> Learning rate schedules and Mamba layer

- mlpf/pyg/PFDataset.py
- mlpf/pyg/inference.py
- mlpf/pyg/mlpf.py
- mlpf/pyg/training.py
- mlpf/pyg/utils.py
- parameters/pyg-cms.yaml
- speed up pytorch inference code by using more efficient awkward calls
- track individual loss components for each particle type
- track (but don't minimize) event-based losses like sliced Wasserstein and MET loss
Training the following mamba-based model:
```
singularity exec --nv ~/HEP-KBFI/singularity/pytorch.simg\:2023-12-06 python3 mlpf/pyg_pipeline.py --config parameters/pyg-cms.yaml --dataset cms --gpus 1 --data-dir ~/tensorflow_datasets/ --train --test --make-plots --conv-type mamba --num-epochs 5 --gpu-batch-multiplier 5 --num-workers 1 --prefetch-factor 10 --ntest 1000 --checkpoint-freq 1 --lr 0.001
```
we are also tracking (but not minimizing) these event-based losses
The performance on QCD-highpT is as follows:
> track individual particle loss components, speedup inference

- mlpf/pyg/training.py
- scripts/tallinn/a100/pytorch.sh
`no_grad` is required around the model forward pass in the validation loop to allow larger batch sizes not to OOM.
> fix torch no grad

- .github/workflows/test.yml
- mlpf/pyg/PFDataset.py
- mlpf/pyg/inference.py
- mlpf/pyg/mlpf.py
- mlpf/pyg/training.py
- mlpf/pyg_pipeline.py
- parameters/pytorch/pyg-clic-hits.yaml
- parameters/pytorch/pyg-clic.yaml
- parameters/pytorch/pyg-cms.yaml
- parameters/pytorch/pyg-delphes.yaml
- scripts/local_test_pyg.sh
- scripts/tallinn/a100/pytorch.sh
- scripts/tallinn/rtx/pytorch.sh
- update to torch 2.2.0 (it was transparent)
- make it possible to use FlashAttention via a config option (requires A100 or better)
- trained the CMS model on ~10% of data with 3 different options
The physics performance on the QCD high-pt sample is as follows.
Mamba (~98M):
GNNLSH (~98M):
FlashAttention (~4M):
Training on the full dataset for 10 epochs (`pyg-cms_20240208_214210_447656`), we get the following performance:
> enable FlashAttention in pytorch, update to torch 2.2.0

- mlpf/data_cms/genjob_pu55to75.sh
- mlpf/data_cms/prepare_args.py
- mlpf/heptfds/cms_pf/cms_utils.py
- mlpf/heptfds/cms_pf/qcd.py
- mlpf/heptfds/cms_pf/ttbar.py
- mlpf/heptfds/cms_pf/ztt.py
- mlpf/plotting/plot_utils.py
- mlpf/pyg/inference.py
- mlpf/pyg/training.py
- mlpf/pyg_pipeline.py
- parameters/pytorch/pyg-cms.yaml
- scripts/fcc/postprocessing.py
- scripts/fcc/submit_postprocessing.sh
- scripts/generate_tfds.sh
- scripts/tallinn/a100/pytorch.sh
- generate more CMS training data, deploy datasets v.1.7.1 to EOS
- speed up CMS tfds production (slowness from `np.append_fields`)
- speed up inference code (slowness from `awkward.from_iter`)
- improve plotting style
- fix start epoch overlapping with the previous epoch when loading a model and continuing training
- fix model loading, do not create empty experiment dirs when not needed (e.g. evaluation)
> clean up loading

- mlpf/data_cms/README.md
- scripts/cmssw/validation_job.sh
Based on the discussion with Andy, the RelVals for the matrix workflows are no longer available (strange).
However, we don't really need the matrix workflows for testing in the first place, it's better and more direct to test directly on GEN-SIM-DIGI-RECO (a la PFValidation).
```
----- Begin Fatal Exception 08-Jul-2024 23:07:06 CEST-----------------------
An exception of category 'FallbackFileOpenError' occurred while
[0] Constructing the EventProcessor
[1] Constructing module: class=MixingModule label='mix'
[2] Calling RootInputFileSequence::initTheFile()
[3] Calling StorageFactory::open()
[4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://xrootd-cms.infn.it//store/relval/CMSSW_13_1_0_pre1/RelValMinBias_14TeV/GEN-SIM/130X_mcRun3_2022_realistic_withNewBSFromEOY2 …
```
> fix CMS instructions

- mlpf/data_cms/postprocessing2.py
- mlpf/heptfds/clic_pf_edm4hep/qq.py
- mlpf/heptfds/clic_pf_edm4hep/ttbar.py
- mlpf/heptfds/cms_pf/cms_utils.py
- mlpf/heptfds/cms_pf/qcd.py
- mlpf/heptfds/cms_pf/ttbar.py
- mlpf/heptfds/cms_pf/vbf.py
- mlpf/plotting/plot_utils.py
- mlpf/pyg/PFDataset.py
- mlpf/pyg/inference.py
- mlpf/pyg/mlpf.py
- mlpf/pyg/training.py
- mlpf/pyg/utils.py
- notebooks/cms/cms-simvalidation.ipynb
- parameters/pytorch/pyg-cms-ttbar-nopu.yaml
- parameters/pytorch/pyg-cms.yaml
- scripts/clic/postprocessing_jobs.py
- scripts/generate_tfds.sh
- scripts/tallinn/a100/pytorch-small-eval-clic.sh
- scripts/tallinn/a100/pytorch-small-eval-cms.sh
- scripts/tallinn/a100/pytorch.sh
- relabel CMS dataset truth during training to be reconstructable
- e.g. sometimes true charged hadrons were associated to calorimeter clusters due to a missing track, in which case we don't want to attempt to reconstruct/hallucinate a charged hadron 
- separate binary ptcl/noptcl and multiclass PID classifiers
- generate v2.1.0 with more stats for CMS
- generate VBF sample with PU
> CMS dataset relabel, generate v2.1.0 with more stats, separate binary classifier

- mlpf/data_cms/genjob_nopu.sh
- mlpf/data_cms/genjob_pu55to75.sh
- mlpf/data_cms/postprocessing2.py
- mlpf/data_cms/postprocessing_jobs.py
- mlpf/data_cms/prepare_args.py
- mlpf/heptfds/cms_pf/cms_utils.py
- mlpf/heptfds/cms_pf/ttbar.py
- mlpf/heptfds/cms_pf/ttbar_nopu.py
- mlpf/pyg/PFDataset.py
- mlpf/pyg/training.py
- notebooks/cms/cms-dataset.ipynb
- notebooks/cms/cms-simvalidation.ipynb
- parameters/pytorch/pyg-clic.yaml
- parameters/pytorch/pyg-cms-ttbar-nopu.yaml
- parameters/pytorch/pyg-cms.yaml
- scripts/generate_tfds.sh
- scripts/local_test_pyg.sh
- scripts/tallinn/a100/pytorch-clic.sh
- scripts/tallinn/a100/pytorch-finetune.sh
- scripts/tallinn/a100/pytorch-small-eval-clic.sh
- scripts/tallinn/a100/pytorch-small-eval-cms.sh
- scripts/tallinn/a100/pytorch.sh
- scripts/tallinn/cmssw-el8.sh
- scripts/tallinn/rtx/pytorch.sh
In the CMS postprocessing script, when a CaloParticle is associated with multiple tracks, break that CaloParticle apart such that each track gets a representative CaloParticle.
This is to improve track to charged hadron reconstruction with the CaloParticle-based merged truth.
Links between CaloParticles, clusters and tracks are augmented via SimClusters.
Before this PR:
After this PR:
> Switch to datasets v2.2.0

- mlpf/data/key4hep/postprocessing.py
- mlpf/heptfds/cld_pf_edm4hep/ttbar.py
- mlpf/heptfds/clic_pf_edm4hep/gamma.py
- mlpf/model/PFDataset.py
Addressing issue https://github.com/jpata/particleflow/issues/333
(Also fixes minor bug regarding the tfds dataset splitting for pipelines where `ntrain`/`nvalid` are given.)
**Changes**
- Wrote a new `postprocessing.py` script to unify the postprocessing of events generated with key4hep under the EDM4HEP format
- The new script can be run with the following choices for `--dataset [clic, fcc]`
The following commands were tested:
**For FCCee dataset postprocessing**
`python mlpf/data/key4hep/postprocessing.py --input /pfvolcentral/data/cld_key4hep/2024_05_full/p8_ee_tt_ecm365/root/reco_p8_ee_tt_ecm365_100038.root --outpath /pfvolcentral/data/cld_key4hep/2024_05_full/p8_ee_tt_ecm365/raw/p8_ee_tt_ecm365/ --dataset fcc`
`tfds build mlpf/heptfds/cld_pf_edm4hep/ttbar --manual_dir …
> Unify key4hep

- mlpf/model/inference.py
- mlpf/model/training.py
- mlpf/plotting/plot_utils.py
- scripts/flatiron/scan_variables.py
Addresses issue https://github.com/jpata/particleflow/issues/390.
When using more than 1 GPU a NCCL timeout error was raised at the end of the first epoch. The issue was not present if I commented out the entire if-block that runs the end-of-epoch tests, including calls to the `run_predictions()` and `make_plots()` functions.
Moving the call to `run_test()`, which contains the calls to `run_predictions()` and `make_plots()` to run on all GPUs instead of just rank 0 solved the issue.
> fix: multi-gpu hang

- mlpf/model/distributed_ray.py
- mlpf/model/inference.py
- mlpf/model/training.py
- mlpf/model/utils.py
- mlpf/pipeline.py
- mlpf/plotting/plot_utils.py
- parameters/pytorch/pyg-cld.yaml
- scripts/local_test_torch.sh
- scripts/tallinn/a100-mig/pytorch-small-eval-clic.sh
- the only supported way to load pretrained weights for evaluation, fine-tuning or continuing a training is `--load`, removing `--fine-tune` and `--resume-training`.
- remove the automatic outdir guessing that was error-prone
- the `--experiment-dir` must be provided manually, or a new directory will be created under `experiments/...`
> remove confusing outdir option

- mlpf/data/cms/postprocessing2.py
We observed a bump at around 50 GeV when plotting the target muon pT spectrum in TTbar events and some assymetry in the target eta distribution for charged pions. When checking the origin of this issue, I noticed that occasionally, caloparticle splitting can happen to tracks that are far separated from the caloparticle. So I added a caloparticle-track delta_r < 0.4 requirement for the splitting to occur. The plots below show the changes in the pT spectrum of muons and eta spectrum of charged pions in TTbar events before and after the fix on the left and right:
Both issues seem to be mitigated by the cut (inspired by the typical jet cone size of 0.4).
On the other hand, since KDTree in sklearn does not accept custom distance metrics, delta R is not computed correctly to take into account …
> Add delta_r selection to caloparticle splitting and fix phi wrap around issue in cms postprocessing
